### ISSUE TITLE
Error I am getting

### ISSUE THREAD

**Issue by chendurkumaran** [yossigo/phonebook_ib_export#2]
vitcc@vitcc:~/Desktop/backup$ python3 export.py 'phonebook.ib' 'chendur.vcf'
Traceback (most recent call last):
  File "export.py", line 92, in <module>
    main()
  File "export.py", line 89, in main
    process(args.infile, args.outfile)
  File "export.py", line 76, in process
    entry = Entry(data)
  File "export.py", line 23, in __init__
    raise ValueError('Invalid entry')
ValueError: Invalid entry

**Comment by ghost** [comment]
hi,
i have the same problem. A solution is?
